# Preset: myconfig
# Saved 2026-03-16 10:09
reward.survival_bonus=0.005
reward.distance_sq_penalty_weight=0.0000005
training.learning_rate=0.00015
training.gamma=0.997
training.gae_lambda=0.98
training.clip_range=0.15
training.n_epochs=8
episode.reward_scale=1.0
reward.dodge_streak_radius_blocks=5
reward.proximity_bonus=0.5
reward.despawn_penalty=100
reward.death_penalty=100
reward.boss_damage_weight=4
training.total_timesteps=10000000
training.n_steps=40960
training.batch_size=1280
episode.max_steps=54000
reward.nohit_kill_bonus=10000
reward.nohit_bonus=1
reward.hit_compounding_penalty=5
reward.wasteful_heal_penalty=1
reward.distance_threshold=240
dodge_streak_radius_blocks=15
training.ent_coef=0.01
reward.player_damage_weight=5
reward.distance_penalty_weight=0
reward.boss_kill_bonus=500
